---
- name: Install and start the Apache service
  hosts: workstation.lab.example.com
  become: true
  tasks:
    - name: Install the Apache service
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Create root directory for web server
      ansible.builtin.file:
        path: /web
        state: directory
        mode: '0755'

    - name: Place index.html content on web server 
      ansible.builtin.copy:
        src: files/index.html
        dest: /web/index.html

    - name: Update root directory in Apache config
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: ^DocumentRoot
        line: DocumentRoot /web

    - name: Enable the Apache service
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: true

    - name: Open http port in firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
